#!/usr/bin/env python

Import("env")
Import("env_modules")

print("SCsub!")

env_sljit = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

thirdparty_dir = "#thirdparty/sljit/src/"

thirdparty_sources = [
    "sljitLir.cpp",
]

env_sljit.Prepend(CPPPATH=[thirdparty_dir])
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]


# Godot source files
module_obj = []

env_sljit.add_source_files(module_obj, "*.cpp")
if env["tests"]:
    env_sljit.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_sljit.add_source_files(module_obj, "./tests/*.cpp")

    if env["disable_exceptions"]:
        env_sljit.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env_sljit.add_source_files(thirdparty_obj, thirdparty_sources)

for source in thirdparty_obj:
    print(source)

for source in module_obj:
    print(source)

env.modules_sources += module_obj
env.modules_sources += thirdparty_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
